version: '2'
services:
  db:
    depends_on:
      - dbdata
    image: mysql
    restart: always
    volumes_from:
      - dbdata
    env_file:
      - ./db.env
  wordpress:
    depends_on:
      - db
    image: wordpress
    volumes:
      - ~/Documents/wordpress:/var/www/html/
    links:
      - db
    ports:
      - "8080:80"
    restart: always
    env_file:
      - ./wordpress.env
  dbdata:
    image: mysql
    volumes:
      - /dbdata
    command: /bin/true
  backup:
    image: aveltens/wordpress-backup
    volumes:
      - ~/Documents/backups:/backups
    volumes_from:
      - wordpress
    links:
      - db:mysql
    restart: always
    env_file:
      - ./backup.env